site_name: Hacking Write-ups
site_url: https://hacking-write-ups.vercel.app
site_description: A collection of awesome write-ups from topics ranging from CVE, vulnHub, CTFs, Hack the box walkthroughs, real-life encounters and everything which can help other enthusiasts learn.
site_author: KK & HZH
repo_url: https://github.com/kangvcar/Hacking-Write-ups
repo_name: Hacking-Write-ups
edit_uri: edit/master/docs/
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
#  font:
#    text: Roboto
#    code: Roboto Mono

  language: zh
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.expand
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - header.autohide
    - content.code.annotate

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kangvcar/Hacking-Write-ups
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/43929500
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCH9jvvcqYaNSCMG6OIRwxvg

extra_css:
  - stylesheets/extra.css

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


copyright: Copyright &copy; 2020 - 2022 Hacking Write-ups

nav:
  - Home:
    - 简介: index.md
    - 贡献指南: contribute.md
    - 讨论交流: discussion.md
    - Markdown 语法: markdown.md
    - Best Book Lists: books.md
    - Changelog: changelog.md
    - License: license.md
  - CVEs:
      - cves/index.md
      - CVE-2022:
        - CVE-2022-25411: cves/CVE-2022/CVE-2022-25411.md
        - CVE-2022-25488: cves/CVE-2022/CVE-2022-25488.md
        - CVE-2022-25578: cves/CVE-2022/CVE-2022-25578.md
        - CVE-2022-26201: cves/CVE-2022/CVE-2022-26201.md
        - CVE-2022-26965: cves/CVE-2022/CVE-2022-26965.md
        - CVE-2022-28060: cves/CVE-2022/CVE-2022-28060.md
        - CVE-2022-28512: cves/CVE-2022/CVE-2022-28512.md
        - CVE-2022-28525: cves/CVE-2022/CVE-2022-28525.md
        - CVE-2022-29464: cves/CVE-2022/CVE-2022-29464.md
        - CVE-2022-30887: cves/CVE-2022/CVE-2022-30887.md
        - CVE-2022-32991: cves/CVE-2022/CVE-2022-32991.md
      - CVE-2021:
        - CVE-2021-44228: cves/CVE-2021/CVE-2021-44228.md
        - CVE-2021-2109: cves/CVE-2021/CVE-2021-2109.md
      - CVE-2020:
        - CVE-2020-14882: cves/CVE-2020/CVE-2020-14882.md
      - CVE-2017:
        - CVE-2017-0143: cves/CVE-2017/CVE-2017-0143.md
        - CVE-2017-10271: cves/CVE-2017/CVE-2017-10271.md
      - CVE-2016:
        - CVE-2016-5195: cves/CVE-2016/CVE-2016-5195.md
  - VulnHub:
      - vulnhub/index.md
      - Jarbas: vulnhub/Jarbas-1.md
      - Wakanda: vulnhub/Wakanda-1.0.md
      - Lampiao: vulnhub/Lampiao-1.0.md
      - IMF: vulnhub/imf.md
      - WordPress2: vulnhub/WordPress2.md
      - Nezuko: vulnhub/Nezuko.md
  - HackTheBox:
      - hackthebox/index.md
      - hackthebox/Nibbles.md
      - hackthebox/Node.md
  - Blogs:
      - blogs/index.md
      - 入门SQL注入: blogs/sql_inject.md
      - 进阶SQL注入: blogs/advance_sql_inject.md
      - 文件上传漏洞: blogs/file_upload.md
      - SUID 提取: blogs/linux_suid.md
      - SUDO 提权: blogs/linux_sudo.md
      - PHP 伪协议: blogs/php_filter.md
      - MS SQL 注入: blogs/mssql_inject.md
      - LDAP 注入漏洞: blogs/ldap_inject.md
  - Tools:
      - tools/index.md
  - Channel: https://t.me/s/hackingwp

